repository:
  url                       : https://github.com/mcmwright/Ashby
html:
  use_repository_button     : true  # Whether to add a link to your repository button
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js